import { useCallback, useEffect, useState } from "react";
import { Activity, BadgeDollarSign, Building2, CheckCircle2, CreditCard, FileCheck2, RefreshCw, ShieldCheck, Users, X } from "lucide-react";
import "../workspace-theme.css";

const API = "https://api.axionenterprise.cloud";
const AUTH = "https://auth.axionenterprise.cloud";
type Overview = { merchants:number; activeKeys:number; chargesToday:number; volumeMonthCents:number; pendingKyc:number; gatewaySubscriptions:number; flowSubscriptions:number };
type Kyc = { authUserId:string; userEmail:string; userDisplayName?:string; legalName:string; tradingName?:string; status:string; documentLastFour:string; billingEmail:string; phoneE164:string; businessDescription:string; submittedAt?:string };
type Transaction = { id:string; correlationId:string; amountCents:string|number; currency:string; status:string; provider:string; createdAt:string; merchantName:string };

async function request(path:string, options:RequestInit={}) {
  const headers = new Headers(options.headers); headers.set("Accept", "application/json");
  if (options.body) headers.set("Content-Type", "application/json");
  const response = await fetch(`${API}${path}`, {...options, headers, credentials:"include"});
  const data = await response.json().catch(() => null);
  if (!response.ok) throw Object.assign(new Error(data?.error?.message || data?.error || `HTTP ${response.status}`), {status:response.status});
  return data;
}

function money(cents:string|number) { return new Intl.NumberFormat("pt-BR", {style:"currency",currency:"BRL"}).format(Number(cents)/100); }

export default function AdminDashboard() {
  const [overview,setOverview]=useState<Overview|null>(null); const [applications,setApplications]=useState<Kyc[]>([]); const [transactions,setTransactions]=useState<Transaction[]>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [forbidden,setForbidden]=useState(false); const [selected,setSelected]=useState<Kyc|null>(null); const [decision,setDecision]=useState("APPROVED"); const [reason,setReason]=useState(""); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [o,k,t]=await Promise.all([request("/v1/internal/admin/overview"),request("/v1/internal/kyc/applications"),request("/v1/internal/admin/transactions")]);setOverview(o.overview);setApplications(k.applications||[]);setTransactions(t.transactions||[]);setForbidden(false);}catch(e:any){if(e.status===403)setForbidden(true);else if(e.status===401)window.location.assign(`${AUTH}/login?return_to=${encodeURIComponent(window.location.href)}`);else setError(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function review(){if(!selected)return;setSaving(true);try{await request(`/v1/internal/kyc/applications/${encodeURIComponent(selected.authUserId)}/review`,{method:"POST",body:JSON.stringify({status:decision,reason:reason.trim()||undefined})});setSelected(null);setReason("");await load();}catch(e:any){setError(e.message);}finally{setSaving(false);}}
  if(forbidden)return <main className="pay-workspace grid min-h-screen place-items-center p-6"><div className="max-w-md rounded-2xl border border-red-400/20 bg-[#09120d] p-8 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-red-300"/><h1 className="mt-5 text-2xl">Acesso administrativo restrito</h1><p className="mt-3 text-sm leading-6 text-[#a1b0a6]">Sua identidade AXION não está cadastrada como revisora KYC.</p></div></main>;
  const cards=[ [Building2,"Merchants ativos",overview?.merchants??0], [FileCheck2,"KYC pendentes",overview?.pendingKyc??0], [Activity,"Cobranças hoje",overview?.chargesToday??0], [BadgeDollarSign,"Volume confirmado no mês",money(overview?.volumeMonthCents??0)], [CreditCard,"Assinaturas Gateway",overview?.gatewaySubscriptions??0], [Users,"Assinaturas Flow",overview?.flowSubscriptions??0] ] as const;
  return <main className="pay-workspace min-h-screen bg-[#040806] text-[#f3f7f4]"><header className="sticky top-0 z-30 border-b border-[#213428] bg-[#040806]/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><a href="/admin" className="flex items-center gap-3"><img src="/axion-logo.png" className="h-11 w-10 object-contain" alt=""/><span className="text-lg font-semibold">AXION Pay <span className="text-[#69f0ae]">Admin</span></span></a><div className="flex items-center gap-3"><span className="hidden items-center gap-2 text-xs text-[#8b9f93] sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#00e66b]"/>Ambiente de produção</span><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-[#30513d] bg-[#101d14] px-3 py-2 text-xs font-semibold"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Atualizar</button></div></div></header>
  <div className="mx-auto max-w-7xl space-y-10 px-5 py-10"><section><p className="font-mono text-xs tracking-[.16em] text-[#69f0ae]">CONTROLE FINANCEIRO E COMPLIANCE</p><h1 className="mt-3 text-3xl sm:text-4xl">Operação AXION Pay</h1><p className="mt-3 text-sm text-[#a1b0a6]">Aprovações KYC, volume processado, cobranças e assinaturas.</p>{error&&<p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}</section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{cards.map(([Icon,label,value])=><article key={label} className="rounded-2xl border border-[#213428] bg-[#09120d] p-5"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-[#69f0ae]"/><span className="font-mono text-[10px] text-[#82998a]">LIVE</span></div><p className="mt-5 text-sm text-[#a1b0a6]">{label}</p><p className="mt-2 text-3xl font-semibold tabular-nums">{value}</p></article>)}</section>
  <section><div className="mb-5 flex items-end justify-between"><div><p className="font-mono text-xs tracking-[.14em] text-[#69f0ae]">COMPLIANCE</p><h2 className="mt-2 text-2xl">Fila de aprovação KYC</h2></div><span className="rounded-full border border-[#30513d] px-3 py-1 text-xs text-[#a1b0a6]">{applications.length} solicitações</span></div><div className="overflow-hidden rounded-2xl border border-[#213428] bg-[#09120d]"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[#213428] bg-[#050c08] font-mono text-[10px] uppercase tracking-wider text-[#82998a]"><tr><th className="p-4">Organização</th><th className="p-4">Contato</th><th className="p-4">Documento</th><th className="p-4">Status</th><th className="p-4 text-right">Ação</th></tr></thead><tbody>{applications.map(a=><tr key={a.authUserId} className="border-b border-[#213428] last:border-0"><td className="p-4"><b>{a.legalName}</b><p className="mt-1 text-xs text-[#8b9f93]">{a.businessDescription}</p></td><td className="p-4 text-[#b5c6bb]">{a.billingEmail}</td><td className="p-4 font-mono text-xs">•••• {a.documentLastFour}</td><td className="p-4"><span className="rounded-full border border-amber-400/25 bg-amber-400/10 px-2.5 py-1 text-xs text-amber-200">{a.status}</span></td><td className="p-4 text-right"><button onClick={()=>setSelected(a)} className="rounded-lg bg-[#00e66b] px-3 py-2 text-xs font-semibold text-[#032111]">Analisar</button></td></tr>)}{!applications.length&&!loading&&<tr><td colSpan={5} className="p-10 text-center text-[#8b9f93]">Nenhuma solicitação na fila.</td></tr>}</tbody></table></div></div></section>
  <section><div className="mb-5"><p className="font-mono text-xs tracking-[.14em] text-[#69f0ae]">FINANCEIRO</p><h2 className="mt-2 text-2xl">Cobranças recentes</h2></div><div className="overflow-hidden rounded-2xl border border-[#213428] bg-[#09120d]"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[#213428] bg-[#050c08] font-mono text-[10px] uppercase tracking-wider text-[#82998a]"><tr><th className="p-4">Merchant</th><th className="p-4">Referência</th><th className="p-4">Provedor</th><th className="p-4">Status</th><th className="p-4 text-right">Valor</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id} className="border-b border-[#213428] last:border-0"><td className="p-4 font-semibold">{t.merchantName}</td><td className="p-4 font-mono text-xs text-[#a1b0a6]">{t.correlationId}</td><td className="p-4 uppercase text-[#b5c6bb]">{t.provider}</td><td className="p-4 text-[#69f0ae]">{t.status}</td><td className="p-4 text-right font-mono">{money(t.amountCents)}</td></tr>)}{!transactions.length&&!loading&&<tr><td colSpan={5} className="p-10 text-center text-[#8b9f93]">Nenhuma cobrança registrada.</td></tr>}</tbody></table></div></div></section></div>
  {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-labelledby="admin-review-title" className="w-full max-w-lg rounded-2xl border border-[#30513d] bg-[#09120d] p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 id="admin-review-title" className="text-xl">Analisar KYC</h2><p className="mt-2 text-sm text-[#a1b0a6]">{selected.legalName} · {selected.userEmail}</p></div><button onClick={()=>setSelected(null)} aria-label="Fechar"><X className="h-5 w-5"/></button></div><div className="mt-6 grid gap-4"><label className="text-sm text-[#b5c6bb]">Decisão<select value={decision} onChange={e=>setDecision(e.target.value)} className="mt-2 w-full rounded-lg border border-[#30513d] bg-[#050c08] p-3 text-white"><option value="APPROVED">Aprovar</option><option value="IN_REVIEW">Manter em revisão</option><option value="ACTION_REQUIRED">Solicitar ajustes</option><option value="REJECTED">Rejeitar</option></select></label><label className="text-sm text-[#b5c6bb]">Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 min-h-28 w-full rounded-lg border border-[#30513d] bg-[#050c08] p-3 text-white" placeholder="Obrigatório para ajustes ou rejeição"/></label></div><div className="mt-6 flex justify-end gap-3"><button onClick={()=>setSelected(null)} className="rounded-lg border border-[#30513d] px-4 py-2.5 text-sm">Cancelar</button><button onClick={()=>void review()} disabled={saving||(["ACTION_REQUIRED","REJECTED"].includes(decision)&&reason.trim().length<3)} className="inline-flex items-center gap-2 rounded-lg bg-[#00e66b] px-4 py-2.5 text-sm font-semibold text-[#032111] disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/>{saving?"Salvando…":"Registrar decisão"}</button></div></section></div>}
  </main>;
}
